#!/usr/bin/env bash

export APP_ENV=${APP_ENV:-local}
export NGINX_PORT=${NGINX_PORT:-80}
export NGINX_ALIAS=${NGINX_ALIAS:-localhost}
export SQL_SERVER_PORT=${SQL_SERVER_PORT:-1443}
export ACCEPT_EULA=${ACCEPT_EULA:-Y}
export SA_PASSWORD=${SA_PASSWORD:-password}
export MAILHOG_PORT=${MAILHOG_PORT:-8025}
export REDIS_PORT=${REDIS_PORT:-6379}

COMPOSE_FILE="dev"

if [ $APP_ENV == "staging" ]; then
    COMPOSE_FILE="staging"
elif [ $APP_ENV == "production" ]; then
    COMPOSE_FILE="production"
fi

COMPOSE="sudo docker compose --env-file .docker/.env -f docker-compose.${COMPOSE_FILE}.yml"

if [ $# -gt 0 ];then

    if [ "$1" == "art" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            php-fpm \
            php artisan "$@"

    elif [ "$1" == "start" ]; then
        shift 1
        $COMPOSE up -d

    elif [ "$1" == "destroy" ]; then
        shift 1
        $COMPOSE down "$@"

    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            php-fpm \
            composer "$@"

    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            php-fpm \
            ./vendor/bin/phpunit "$@"

    elif [ "$1" == "pint" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            php-fpm \
            ./vendor/bin/pint "$@"

    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            npm "$@"

    else
        $COMPOSE "$@"
    fi

else
    $COMPOSE ps
fi
